#!/usr/bin/env python3
"""render_codex_work_skill.py — generate Codex work skill from Claude work skill.

AUTO-GENERATED from global-memory/skills/work/SKILL.md is written into the
generated artifact as a drift guard for humans and tests.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "skills" / "work" / "SKILL.md"
ADAPTER = REPO / "skills" / "work" / "codex-adapter.md"
DEFAULT_DEST = Path.home() / ".codex" / "skills" / "codex-work" / "SKILL.md"

FRONTMATTER = """---
name: codex-work
description: Formal task-governance workflow for Codex, generated from the shared Work Mode source. Use when the user asks to start, continue, migrate, or run a multi-turn development/debugging/documentation task with persistent task docs, especially requests like "/work", "走 work 流程", "新开任务", "继续任务", "按设计文档推进", or "收尾/归档". Do not use for quick one-off answers, simple shell commands, trivial edits, or casual discussion.
---
"""

NOTICE = """<!-- AUTO-GENERATED from global-memory/skills/work/SKILL.md. Do not edit this file directly. -->
<!-- Rebuild with: python D:\\global-memory\\harness\\scripts\\render_codex_work_skill.py -->
"""


def strip_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end == -1:
        return text
    return text[end + len("\n---\n") :]


def render(source_path: Path = SOURCE, adapter_path: Path = ADAPTER) -> str:
    source = strip_frontmatter(source_path.read_text(encoding="utf-8")).strip()
    adapter = adapter_path.read_text(encoding="utf-8").strip()
    return (
        FRONTMATTER
        + "\n"
        + NOTICE
        + "\n# Codex Work\n\n"
        + "Use this skill to run the shared Work Mode workflow in Codex. The shared source is rendered below; the Codex Adapter has precedence where behavior differs.\n\n"
        + adapter
        + "\n\n---\n\n"
        + "## Shared Work Mode Source\n\n"
        + source
        + "\n"
    )


def write_if_changed(dest: Path, content: str) -> bool:
    old = dest.read_text(encoding="utf-8") if dest.exists() else None
    if old == content:
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--adapter", type=Path, default=ADAPTER)
    parser.add_argument("--dest", type=Path, default=DEFAULT_DEST)
    parser.add_argument("--check", action="store_true", help="fail if generated output differs from destination")
    args = parser.parse_args(argv)

    content = render(args.source, args.adapter)
    if args.check:
        if not args.dest.exists():
            print(f"codex-work drift: missing {args.dest}", file=sys.stderr)
            return 1
        current = args.dest.read_text(encoding="utf-8")
        if current != content:
            print(f"codex-work drift: regenerate {args.dest}", file=sys.stderr)
            return 1
        print("codex-work generated skill is up to date")
        return 0

    changed = write_if_changed(args.dest, content)
    print(("updated" if changed else "unchanged") + f": {args.dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
